solution:			solution.c
					gcc solution.c -o solution

#solution_server:	solution_server.c
#					gcc solution_server.c -o solution_server
#
#shm_server:			shm_server.c
#					gcc shm_server.c -o shm_server
#
#shm_client:			shm_client.c
#					gcc shm_client.c -o shm_client
