long_text_util:		long_text_util.c
					gcc long_text_util.c -o long_text_util

symbol_count:		symbol_count.c
					gcc symbol_count.c -g3 -o symbol_count

mulriplexing:		multiplexing.c
					gcc multiplexing.c -o multiplexing

