version: '2'
services:
    stepik_linux_ubuntu:
        container_name: stepik_linux_ubuntu
        build: .
        volumes: 
            - .:/root/stepik_linux
        security_opt:
            - seccomp:unconfined
