ppid:			ppid.c
				gcc -o ppid ppid.c

proc_list:		proc_list.c
				gcc -o proc_list proc_list.c

pid_tree:		pid_tree.c
				gcc -o pid_tree pid_tree.c

children_count: children_count.c
				gcc children_count.c -o children_count

daemon:			daemon.c
				gcc daemon.c -o daemon
